### PR TITLE
Reclassify contract's category

### LINKED ISSUE #19: question on classification of the vulnerability
I have a question on the classification for the vulnerability in [dataset/unchecked_low_level_calls/FibonacciBalance.sol](https://github.com/smartbugs/smartbugs/blob/master/dataset/unchecked_low_level_calls/FibonacciBalance.sol). I wonder whether the current classification for this file is good enough.

According to [DASP](https://dasp.co/#item-4), ``unchecked low level calls`` refers to cases where failing cases (i.e., returning ``false``) are not properly handled.

However, I think the [relevant document](https://github.com/sigp/solidity-security-blog#4-delegatecall-1) related to the benchmark above is about incorrect mapping of state variables or access control vulnerabilities, rather than unchecked return values.

### PR DESCRIPTION
**Pull request by jff**
Reclassify contract's category from 'unchecked_low_level_calls' to 'access_control' (FibonacciBalance.sol).

Closes #19

### CODE REVIEW

**Comment by jff** [comment]
This one needs discussion. See issue #19

**Comment by jff** [comment]
To help with the discussion, see also the [mapping that we created](https://github.com/smartbugs/smartbugs/wiki/Vulnerabilities-mapping).

**Comment by pedrocrvz** [comment]
I agree with reclassification to `access_control`. The mapping we created indeed refers this type of vulnerability as such.
Although the vulnerability is regarding a low level call (`DELEGATECALL`), it is **not referent to unchecked** low level calls but the context it is ran (also see issue #15).

**Comment by ruimaranhao** [comment]
Agree with @pedrocrvz.

**Pull request merged**
