### PR TITLE
Add smartcheck extended

### PR DESCRIPTION
**Pull request by jff**

### CODE REVIEW

**Comment by jff** [comment]
@tdurieux : should we keep `smartcheck` and rename this to `smartcheck-extended`?

**Comment by jff** [comment]
NOTE: The parser that we wrote for Smartcheck can no longer be used for this Smartcheck-extended (we are now using a more recent version of Smartcheck that produces a different output).

This means that if we want to include smartcheck-extended, we need to write a new parser.

**Comment by tdurieux** [comment]
You included ethor changes in the PR.

**Comment by tdurieux** [comment]
> NOTE: The parser that we wrote for Smartcheck can no longer be used for this Smartcheck-extended (we are now using a more recent version of Smartcheck that produces a different output).
> 
> This means that if we want to include smartcheck-extended, we need to write a new parser.

I see, that is not ideal. In this case, do you think smartcheck-extended has some value for the community? If not, it is better to not include it.

**Comment by jff** [comment]
Close this now and reassess later if we want to extend latest version of smartcheck.

**Pull request closed without merging**
