### PR TITLE
Fixed: HTTP connection error, output for Mythril timeout

### PR DESCRIPTION
**Pull request by gsalzer**
Issue #72 reports http connection read time outs. As it turns out, they occur whenever a timeout occurs, as container.wait signals the timeout by some internal exception, which was caught, but the internal error was printed.
The Mythril output was not always treated satisfactory when an error occurred, as tracebacks and json output can exist side by side in Mythril output

### CODE REVIEW

**Comment by gsalzer** [comment]
commit 4bf9c57 improves the handling of Mythril output
[commit b8ab589](https://github.com/smartbugs/smartbugs/pull/92/commits/b8ab589bdf25b0b4fc37f3be87a4dee0126d8069) adds a field `findings` to result.json, which contains a list of labels identifying the vulnerabilities or other findings. Currently only implemented for Mythril and Conkas.

**Comment by tdurieux** [comment]
Looks good to me. @jff if it is good to you, you can merge

**Comment by jff** [comment]
Thanks @gsalzer! It also looks good to me. This changes the way in which tools are now added, right? When adding a new tool, the goal is to initialize properly `self.output`, `self.labels`, and `self.success`, correct?

**Comment by gsalzer** [comment]
@jff Yes, integrating a new tool requires to write a function `__parse_output` that determines the analysis results (`output`), whether errors occurred (`success`), and a set of keywords (`labels`) describing the findings. The purpose of the latter is to obviate the need to parse `result.log` a second time (or to understand the tool-specific `analysis` of `result.json`) , e.g. for comparing tools (like we plan to do) or for selecting contracts based on the analysis results of tools; the general parts of `result.json` suffice.

**Pull request merged**
