### PR TITLE
Add more vulnerable contracts to curated dataset

### PR DESCRIPTION
**Pull request by jff**
This extends the curated dataset with 74 contracts. @pedrocrvz created this dataset as part of his MSc project.

### CODE REVIEW

**Comment by tdurieux** [comment]
https://github.com/smartbugs/smartbugs/blob/master/dataset/vulnerabilities.json should also be updated.

**Comment by jff** [comment]
Should we also update the vulnerabilities.json file?

**Comment by tdurieux** [comment]
Yes

**Comment by jff** [comment]
Done. I ran the script. Indentation is not great, but the file was updated.

**Comment by ruimaranhao** [comment]
Can you run some sort of json pretty-printer?

**Comment by jff** [comment]
Done that, please check.

**Pull request merged**
