### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by ruimaranhao**
adding license.

### CODE REVIEW

**Comment by jff** [comment]
Please change things like: 

>   Copyright [yyyy] [name of copyright owner]

**Comment by ruimaranhao** [comment]
It is part of the license. It is supposed to be like that.

**Comment by jff** [comment]
Yes, sorry. The previous file had that info :)

Are we supposed to add the Copyright notice to each file in the repo?

**Comment by ruimaranhao** [comment]
I don't think so.

**Pull request merged**
