### PR TITLE
Update four findings for Slither, and the corresponding SWC, DASP IDs.

### PR DESCRIPTION
**Pull request by MarkLee131**
Hi, I find that the current Finding mappings lack these four vulnerability identifiers for Slither, which would result in the parsing failure. 
I have updated them into Slither's `findings.yaml` and mapped the corresponding SWC and DASP IDs according to Slither's doc.

Hope it helps.

```
cache-array-length: {}
cyclomatic-complexity: {}
immutable-states: {}
return-bomb: SWC-128, DASP-5
```

### CODE REVIEW

**Comment by MarkLee131** [comment]
Hi, @gsalzer. Just a gentle ping on this pull request. Could you let me know if there is any feedback or additional changes needed? Thanks!

**Comment by gsalzer** [comment]
@MarkLee131 Thanks for your extension. Are you using the Docker image that is configured in Smartbugs or a newer one? My impression is that these four additional findings pertain to a newer version. It would make sense to update the image as well.

**Comment by gsalzer** [comment]
@MarkLee131 The version of Slither in Smartbugs, 0.6.1, does not seem to know about the four extra findings you add. The current version of Slither, 0.10.0, includes them, but the format of the output has changed considerably, so there needs to be changed more in the parser.

**Comment by gsalzer** [comment]
I have added Slither 0.10.0 to the supported tools, with an updated parser. For the moment, I do not add the SWC- and DASP classification to `return-bomb`, because I'm not yet convinced that these classifications match.
According to the wiki of Slither, `return-bomb` means that the callee receives all the remaining gas and may burn it. SWC-128, on the other hand, refers to the block gas limit, which is related to unbounded loops. DASP-5 is a generic DoS error, which may fit. But is a callee burning all gas always a DoS attack?

**Comment by gsalzer** [comment]
Finally, I didn't use your commits, as I extracted the findings automatically from the detectors of Slither, to make sure that I don't miss one. But your pull request contributed to Smartbugs, as it is the cause for the update. Thanks!
I'd appreciate if you could test the updated version of Slither, which is available via `smartbugs -t slither`.

**Comment by MarkLee131** [comment]
Got it, and totally agree with your refined idea to update slither's findings. Hope to help in the future.  :)

**Pull request closed without merging**
