### PR TITLE
Fix vulnerable_at_lines and issue #29

### PR DESCRIPTION
**Pull request by nveloso**
Hi! I fixed two contracts that have comments with wrong lines. Also I fixed the issue #29

### CODE REVIEW

**Comment by pedrocrvz** [comment]
LGTM. 
I think we need to update the table with the number of vulns, since `insecure_transfer` now has one less vulnerability. or maybe even run the script. tagging @jff about this.

**Comment by jff** [comment]
Thanks for the corrections, @nveloso! They look good to me. Could you please update the vulnerabilities.json file as well? You can use the script `get_vulns_lines.js` (please use pretty printing -- e.g. `python -m json.tool`).

**Comment by nveloso** [comment]
When a contract has more than one vulnerability it should be like this:
```
{
    "name": "0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "path": "dataset/reentrancy/0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "source": "etherscan.io",
    "vulnerabilities": [
        {
            "lines": [
                94
            ],
            "category": "reentrancy"
        }
    ]
},
{
    "name": "0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "path": "dataset/unchecked_low_level_calls/0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "source": "etherscan.io",
    "vulnerabilities": [
        {
            "lines": [
                44
            ],
            "category": "unchecked_low_level_calls"
        }
    ]
}
```
or it should be like this:
```
{
    "name": "0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "path": "dataset/?????????????????????????????/0x627fa62ccbb1c1b04ffaecd72a53e37fc0e17839.sol",
    "source": "etherscan.io",
    "vulnerabilities": [
        {
            "lines": [
                94
            ],
            "category": "reentrancy"
        },
        {
            "lines": [
                44
            ],
            "category": "unchecked_low_level_calls"
        }
    ]
}
```

**Comment by jff** [comment]
@nveloso You can use the output of the script (and then pretty print it). Thanks!

**Review by jff — APPROVED** [review]
Thank you!

**Pull request merged**
